version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx/mycoupon:/var/log/nginx/mycoupon
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - springboot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - my_network

  springboot:
    image: happine2s/mycoupon
    ports:
      - "8080:8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge