spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    thymeleaf:
      cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update # 첫 배포 이후 validate 으로 수정

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: ${KAKAO_CLIENT_AUTHENTICATION_METHOD}
            scope: ${KAKAO_SCOPE}
            authorization-grant-type: ${KAKAO_AUTH_GRANT_TYPE}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

    data:
      redis:
        port: ${REDIS_PORT}
        host: ${REDIS_HOST}

  jwt:
    key: ${JWT_KEY}