spring:
  datasource:
    url: jdbc:mysql://{RDS_endpoint}/{RDS_database}
    username: {RDS_user}
    password: {RDS_pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update