
name: CI/CD with Gradle

on:
  push:
    branches: ["main", "cicd"]
  pull_request:
    branches: ["main", "cicd"]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: create deploy directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_NAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p /home/ubuntu/deploy

      - name: copy docker-compose.yml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_NAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/deploy/"

      - name: Create custom Docker network
        run: docker network create app-network

      - name: Docker build and push
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} .

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: docker Hub push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

  deploy:
    needs: build-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_NAME }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> ~/deploy/.env
            echo "DOCKER_REPO=${{ secrets.DOCKER_REPO }}" >> ~/deploy/.env
            echo "DB_URL=${{ secrets.DB_URL }}" >> ~/deploy/.env
            echo "DB_USER=${{ secrets.DB_USER }}" >> ~/deploy/.env
            echo "DB_PWD=${{ secrets.DB_PWD }}" >> ~/deploy/.env
            echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> ~/deploy/.env
            echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> ~/deploy/.env
            echo "JWT_SECRET_KEY=${{ secrets.JWT_KEY }}" >> ~/deploy/.env
            
            sudo docker-compose -f ~/deploy/docker-compose.yml pull
            sudo docker-compose -f ~/deploy/docker-compose.yml up -d
            sudo docker image prune -f